### ISSUE TITLE
Vertical Metrics in general font info

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/opensans-1#13]
Basic ascender 2189 and descender -600 do not add up to UPM 2048.

Double check that these values are consistent with the originals.

![Open Sans 2020-04-20 at 9 31 34 PM](https://user-images.githubusercontent.com/6576107/79817324-369cee80-8353-11ea-95ca-07e0afe1c865.png)

**Comment by pichotta** [comment]
Double check and compare general font Ascender and Descender values between what is currently being served and the most recent source files.

![OpenSans check vert metrics](https://user-images.githubusercontent.com/6576107/80922643-806ed700-8d4c-11ea-83f3-c616eab403e7.png)

**Comment by moyogo** [comment]
Looking at the fonts currently served.
The Typo metrics now match the previous Win metrics. But the Win Descent is now 860 instead of 600.

@m4rc1e Shouldn’t the Win Descent be 600?

**Comment by moyogo** [comment]
@pichotta we had a chat with @m4rc1e and the conclusion was that the win Descent doesn’t affect line heights in browsers because fsSelection bit-7 is enabled, and the line height matched the fonts being served.
