### ISSUE TITLE
Word space: nb space

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/opensans-1#19]
In four of the italic styles the nbspace has a different set width than space.

CondSemiBolditalic
CondExtraBoldItalic
CondLightItalic
CondBoldItalic

**Comment by moyogo** [comment]
Now that CondExtraBoldItalic, CondBoldItalic, CondSemiBoldItalic, CondItalic and CondLightItalic are dropped from the generated fonts, this can be fixed when the CondExtraBoldItalic master is fixed.

**Comment by pichotta** [comment]
Change /nbspace in the CondLightItal from an advanced with of 479 to 346 to match the /space.  

Presumably when a new CondExtraBoldItalic is drawn and added to the space the /nbspace and /space will have the same advance width.
