### ISSUE TITLE
Horizontal Metrics

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/opensans-1#2]
Double-check set widths of interpolated intermediates against the original spacing.

**Comment by pichotta** [comment]
@davelab6
@m4rc1e
@moyogo 

Looking into the advance width (set width) of the TTFs generated from the new masters and comparing them with the TTFs currently being served on fonts.google.com.  
First tests show inconsistencies reported in all masters and intermediates. e.g. OpenSans-Light

In this list:
First advance width value is from newly generated TTF
Second advance width value is from TTF currently being served
e.g. uni03D1 current advwidth is 1238, f.g.c advwidth is 1208

**OpenSans-Light.ttf**
` grave 9 1182
j j 426 463
¨ dieresis 1266 1182
¯ macron 52 overscore 1024
´ acute 9 1182
¸ cedilla 445 420
¼ onequarter 1592 1516
½ onehalf 1592 1516
¾ threequarters 1592 1516
ĳ ij 889 926
ĵ jcircumflex 426 463
ǰ uni01F0 426 463
ȷ uni0237 426 dotlessj 463
ʼ uni02BC 310 297
ˆ circumflex 582 1182
ˇ caron 582 1182
ˉ uni02C9 1155 macron 1141
˘ breve 56 1182
˙ dotaccent 389 483
˚ ring 4 1182
˛ ogonek 8 356
˜ tilde 93 1182
˝ hungarumlaut 1162 1182
΄ tonos 1123 1182
΅ dieresistonos 1133 1182
Έ Epsilontonos 1130 1221
Ή Etatonos 1473 1563
Ί Iotatonos 516 602
Ό Omicrontonos 1565 1577
Ύ Upsilontonos 1081 1321
Ώ Omegatonos 1587 1608
ϑ uni03D1 1238 1208
ϒ uni03D2 1081 1104
ϖ uni03D6 1594 1587
ј uni0458 426 afii10105 463
Ѣ uni0462 1345 1378
ѣ uni0463 1195 1241
Ѳ uni0472 1551 1565
ѳ uni0473 1166 1200
Ѵ uni0474 1267 1210
ѵ uni0475 1000 973
Ѷ uni0476 1267 1210
ѷ uni0477 1000 973
ѹ uni0479 2140 2093
҃ uni0483 0 1141
҄ uni0484 0 1182
҅ uni0485 0 1182
҆ uni0486 0 1182
҉ uni0489 1989 1958
һ uni04BB 1208 1167
Ө uni04E8 1551 1565
ө uni04E9 1166 1200
Ӫ uni04EA 1551 1565
ӫ uni04EB 1166 1200
Ӽ uni04FC 1102 1192
ӽ uni04FD 1020 1036
Ὅ uni1F4D 1565 1632
Light.ttf
⁄ fraction 216 246
₤ lira 1126 afii08941 1169
₫ dong 1203 uni20AB 1219
⅛ oneeighth 1592 1516
⅜ threeeighths 1592 1516
⅝ fiveeighths 1592 1516
⅞ seveneighths 1592 1516

/grave/j/dieresis/macron/acute/cedilla/onequarter/onehalf/threequarters/oneeighth/threeeighths/fiveeighths/seveneighths/ij/jcircumflex/uni01F0/uni0237/uni02BC/circumflex/caron/uni02C9/breve/dotaccent/ring/ogonek/tilde/hungarumlaut/tonos/dieresistonos/Epsilontonos/Etatonos/Iotatonos/Omicrontonos/Upsilontonos/Omegatono/uni03D1/uni03D2/uni03D6/uni0458/uni0462/uni0463/uni0472/uni0473/uni0474/uni0475/uni0476/uni0477/uni0479/uni0483/uni0484/uni0485/uni0486/uni0489/uni04BB/uni04E8/uni04E9/uni04EA/uni04EB/uni04FC/uni04FD/uni1F4D/fraction/lira/dong/

![OpenSansLight advwidth comparison](https://user-images.githubusercontent.com/6576107/81250248-7835c680-8fee-11ea-931a-30edf6e21f92.png)

**Comment by pichotta** [comment]
![OpenSansRegularComparison](https://user-images.githubusercontent.com/6576107/81251038-635a3280-8ff0-11ea-9b5c-4e081909a08d.png)

**Comment by pichotta** [comment]
In the Regular TTF the advanced widths are different for all of the UC and lc.  
The side bearings of the Uppercase /O are almost equal but the adv width is different because the actual width of the /O outline is slightly more narrow in the new version. 
This would suggest some kind of previous manual adjustments in the intermediates; scaling; or tracking; or?

I checked the amount of difference in the adv widths between the served and new versions.
Most of the key glyphs in both the instances and masters, have as much as an 80 unit difference.

for e.g. in the Regular, the UC and lc advance widths are within a 35 unit threshold. To include the Gr and Cy the threshold is 55. And to include all glyphs (with the exception of seven glyphs and with the exception of the floating diacritics the threshold is 80). I mention this if the consideration is to use a sparse master.


![OpenSans Regular UC O](https://user-images.githubusercontent.com/6576107/81359165-631c6e80-90a6-11ea-9e31-333cf52b2977.png)

**Comment by davelab6** [comment]
If an intermediate master is added and the only deltas are to the advanced width values and the x dimension position of all points, I'm guessing that the increase in file size to the gvar table maybe small and deliver completely identical metrics for the named instance, although I'm not sure what happens with the Kerning....

Since the overarching goal is quality improvements, then I wonder if the newly interpolated outlines and metrics and kerning are from a typographic point of view an improvement. If it is really the case, then the changes are worth making, and any file size increase to recreate the old less good design is a waste.

**Comment by davelab6** [comment]
From what I'm saying the shape differences are extremely minor and it's really only an issue with document reflow, which the kind of respacing sparse master I described could address.

**Comment by pichotta** [comment]
This family has no kerning.

Here is a comparison of the advance width differences for the masters and instances.

[OpensSans_Compare_AdvanceWidths.txt](https://github.com/TypeNetwork/opensans-1/files/4599337/OpensSans_Compare_AdvanceWidths.txt)

**Comment by davelab6** [comment]
> This family has no kerning.

HMM! That surprises me. 

I noticed today that what GF currently 'inputs' into our system (available from https://github.com/google/fonts, are "OLD" in the below) is different to what we 'output' from fonts.google.com in a download zip, after passing through some internal systems (the "NEW" files in the below)

I see the difference is that the 'legacy' kerning table is missing in the NEW version, plus some metadata changes.

```
python3 fbdiff.py OLD/OpenSans-Regular.ttf NEW/OpenSans-Regular.ttf;
Tables only in font A:
  DSIG, kern

Different tables:
           A     B
  GDEF    30    46 bytes
  GPOS    56    16 bytes
  GSUB   966   750 bytes
  OS/2    96    96 bytes
  cmap  1050   904 bytes
  head    54    54 bytes
  name  1479   978 bytes
  post  9771  7939 bytes

Identical tables:
  cvt , fpgm, gasp, glyf, hhea, hmtx, loca, maxp, prep
```

Looking at the Regular, I see the Full Name was/is

      Open Sans
      Open Sans Regular

PS Name

      OpenSans
      OpenSans-Regular

Looking at the Light style, there were no changes. 

I'm guessing that you are comparing what you have to the "NEW" fonts, where the legacy `kern` table is dropped. 

It looks like there was no `GPOS` kerning in either case. 

So, I expect the `kern` table kerns can be imported; and perhaps it may have already been done in the Open Sans Hebrew glyphs sources?

**Comment by davelab6** [comment]
@pichotta I'm curious what the status of this is? :)

**Comment by pichotta** [comment]
@davelab6
See email from @m4rc1e on Fri. May 15.  A couple decisions to be made by Google about how to handle: 
outlines of interpolated instances; 
differences in advance widths;
 previously stripped kerning and kerns for Hebrew.

**Comment by davelab6** [comment]
@m4rc1e please post here

**Comment by m4rc1e** [comment]
Let me open up a separate issue to discuss these points.
