### ISSUE TITLE
Cond: generated TTFs and OTFs

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/opensans-1#20]
Check for missing styles for symmetrical design space for Condensed styles:
OpenSans-CondensedItalic
OpenSans-CondensedSemiBold
OpenSans-CondensedBold
OpenSans-CondensedExtraBold

Currently these binaries were generated:
_OpenSans-CondensedLight.ttf
OpenSans-CondensedLightItalic.ttf
OpenSans-Condensed(Regular).ttf
OpenSans-CondensedBoldItalic.ttf
OpenSans-CondensedSemiBoldItalic.ttf
OpenSans-CondensedExtraBoldItalic.ttf_

**Comment by moyogo** [comment]
This should be fixed with PR #16.

**Comment by pichotta** [comment]
@moyogo 

The Condensed are currently out of scope but a couple notes while we are here, and before we close this Issue.

The three bogus italic styles have been removed.
_OpenSans-CondensedBoldItalic
OpenSans-CondensedSemiBoldItalic
OpenSans-CondensedExtraBoldItalic_

Curious why the otf and ttf folders are missing the binary files for the 'CondBold' and 'CondExtraBold' if they exist as master sources? 

![OpenSans Cond roman binaries](https://user-images.githubusercontent.com/6576107/81106176-1fc5d280-8ee3-11ea-8376-fe9dc4501d45.png)

**Comment by moyogo** [comment]
I opened PR #24 which removes the Cond and CondItalic instances from the build. The designspaces still have them for future work.

**Comment by pichotta** [comment]
Noting here the related Issue #8 
https://github.com/TypeNetwork/opensans-1/issues/8

The OpensSans-CondensedBoldItalic in the sources folder is not a viable master in its current condition.
