### ISSUE TITLE
Glyphs:  Italic forms

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/opensans-1#23]
Double check these differing italic forms are intentional.

/uni0453
/uni045D

![cy ital forms](https://user-images.githubusercontent.com/6576107/80922838-9af58000-8d4d-11ea-8c33-2c85dece75f7.png)

**Comment by moyogo** [comment]
These are cursive forms that are used when the italic is more cursive than slanted.
See for example in Noto Sans, Noto Serif, Brill, Source Sans, Source Serif:
<img width="174" alt="image" src="https://user-images.githubusercontent.com/1923747/80984860-55f14c80-8e26-11ea-8c0c-9e855a8787ed.png">
