### ISSUE TITLE
V1 Regressions: Interpolated instances, metrics and kerning

### ISSUE THREAD

**Issue by m4rc1e** [TypeNetwork/opensans-1#25]
I received a mail from Jill regarding some regressions which are present in the variable font.

---

**Email content:**

**Glyph Set**
new Hebrew glyphs added in new which are not in served fonts, plus a few more

**Interpolated instances (Regular)**
orange = served on fgc
purple = new interpolated instance

At one point in time maybe Regular was either a master? or manually adjusted?
e.g. the actual width of the /O outline is slightly more narrow in the new version
interpolated stem weight consistent but differences in contrast/joins, some shapes e.g. now a kink in /s diagonal

![image](https://user-images.githubusercontent.com/7525512/82568666-12614700-9b77-11ea-99e3-95e52bf4f9f3.png)

These styles are the current interpolated instances
OpenSans-Light.ufo
OpenSans-LightItalic.ufo
  OpenSans-Bold.ufo
OpenSans-ExtraBold.ufo
OpenSans-ExtraBoldItalic.ufo

**Horz metrics**
consistent in poles with exception of these glyphs
floating diacritics, fractions, tonos glyphs, ffligs, ϑ ϒ ϖ ј Ѣ ѣѲѳ Ѵ ѵѶѷ Ѹ ѹһ Өө Ӫ ӫ Ӽ ӽ Ὅ u⁄₤ ₫

differences in adv width for most glyphs in the instances. Most within a threshold of 10 to 80 units

**Kerning**
no kerning in served at fgc
legacy kerning table exists in the input fonts at https://github.com/google/fonts
copied legacy kerning would not cover added Hebrew glyphs
legacy kerning stripped out in laerm0 in this commit. source: remove kerning csv files master (#27)
https://github.com/laerm0/opensans/commit/19799a65a6c6d6d0a5634786c5f4d28aab84082b

![image](https://user-images.githubusercontent.com/7525512/82568697-1c834580-9b77-11ea-818e-9611dbfb85f7.png)

**Comment by m4rc1e** [comment]
Here are my thoughts on the above issues. @davelab6 may disagree.

> **Glyph Set**
> new Hebrew glyphs added in new which are not in served fonts, plus a few more

Seems we wanted to add the Hebrew back in 2017, https://github.com/google/fonts/issues/1258. I'd keep it.

I think Micah included further math glyphs because he received an email from a professor a while back. I'm against adding these glyphs because they won't work correctly. We'd need to add an OT math table.


> **Interpolated instances (Regular)**
> orange = served on fgc
> purple = new interpolated instance

> At one point in time maybe Regular was either a master? or manually adjusted?
> e.g. the actual width of the /O outline is slightly more narrow in the new version
interpolated stem weight consistent but differences in contrast/joins, some shapes e.g. now a kink in /s diagonal

We discovered that the original family may have started off as a multiple master but then they may have tweaked the instances by hand afterwards, https://github.com/laerm0/opensans/issues/21

I suggest we try and keep the outline regressions as minimal as possible. However, I don't think it is worth adding bracket layers to individual glyphs since this may take too long and will increase the file size.

 
> **Horz metrics**
> consistent in poles with exception of these glyphs
floating diacritics, fractions, tonos glyphs, ffligs, ϑ ϒ ϖ ј Ѣ ѣѲѳ Ѵ ѵѶѷ Ѹ ѹһ Өө Ӫ ӫ Ӽ ӽ Ὅ u⁄₤ ₫

> differences in adv width for most glyphs in the instances. Most within a threshold of 10 to 80 units

I reckon some of the advance widths may have changed because Micah may have been fixing existing issues. If you feel the changes are not an improvement, I would change them back in order to minimise regressions.

 > Kerning
> no kerning in served at fgc
legacy kerning table exists in the input fonts at https://github.com/google/fonts
copied legacy kerning would not cover added Hebrew glyphs
legacy kerning stripped out in laerm0 in this commit. source: remove kerning csv files master (laerm0#27)
laerm0@19799a6

Since Open Sans on Google Fonts has its kerning stripped out, I personally wouldn't add any. I also don't know if the quality of the kerning is any good either.

**Comment by davelab6** [comment]
> I think Micah included further math glyphs because he received an email from a professor a while back. I'm against adding these glyphs because they won't work correctly. We'd need to add an OT math table.

If they require a MATH table to be useful, they should not be included. 

> the original family may have started off as a multiple master but then they may have tweaked the instances by hand afterwards

Confirmed, the client Google team requested these tweaks at the time. The client team is no longer using the fonts, so we can remove these inconsistencies if it will improve the overall family design while being a minimal/acceptable regression, as you said.

> If you feel the changes are not an improvement, I would change them back in order to minimise regressions.

Agreed.

> Since Open Sans on Google Fonts has its kerning stripped out, I personally wouldn't add any. I also don't know if the quality of the kerning is any good either.

At this point, I agree no kerning should be added. I think there is clearly an opportunity to kern Open Sans to make it a higher quality typeface family, but it is now much more important to ship the update.

**Comment by pichotta** [comment]
@m4rc1e  
Is there a scenario, user, or application that could test to see if the different horizontal metrics for the OpenSans intermediates causes a significant regression issue?

We are running a test to check the range of the file size — comparing the current clean VF to a VF which includes the Reg and Semibold intermediates as additional masters.

**Comment by moyogo** [comment]
> If they require a MATH table to be useful, they should not be included.

The math glyphs that would require a MATH table are not present.

The glyphs that require the MATH table are typically superscripts of superscripts, subscripts of subscripts, brackets or parentheses in multiple sizes. But these are not in the fonts.

**Comment by pichotta** [comment]
Investigating the side bearings and advance widths differences between what is being served and the current OpenSans. 

1)  For many glyphs it is hard to visually detect the differences of adv widths. The UPM is 2048 so a difference of 50units would be equivalent to 25units on 1000UPM. 
![OpenSans L](https://user-images.githubusercontent.com/6576107/83547202-dc558880-a4cf-11ea-9d4f-a3c45efc6e62.png)



2) The difference in horizontal metrics has less to do with the side bearing values but instead have to do with the width of the char outlines. **So, forcing metrics would not be an effective solution**. The width differences of the outlines is what changes the line length the most.

![OpenSans D](https://user-images.githubusercontent.com/6576107/83547437-36564e00-a4d0-11ea-8189-85af0a17110e.png)
![OpenSans D width](https://user-images.githubusercontent.com/6576107/83547451-39e9d500-a4d0-11ea-8dfa-4ab24a895e76.png)




3) Some spacing differences result in a more open fit (uni04C5) and some less (uni04FC, which has a tight rsb).
![OpenSans uni04C5](https://user-images.githubusercontent.com/6576107/83549102-c3020b80-a4d2-11ea-825e-38e375ccdc3a.png)

![OpenSans uni04FC](https://user-images.githubusercontent.com/6576107/83549113-c5fcfc00-a4d2-11ea-90a0-7e27cd90df12.png)



4) The floating accents are on different widths from both each other and between versions, and not centered. The accented glyphs are composed of both floating diacritics and combining accents. The fractions have been loosened. 

![OpenSans accent composition](https://user-images.githubusercontent.com/6576107/83550212-7cadac00-a4d4-11ea-9f51-9abf045ae070.png)

cc: 
@davelab6 
@m4rc1e 
@moyogo 
@djrrb

**Comment by pichotta** [comment]
Exploring the option of using the NotoSans data to replace current OpenSans data. After scaling of the UPM and some adjustments the fidelity between two is almost an exact match with some added benefits.

Here is a screen shot comparing the outlines of the Light (which is an interpolated master)
Preliminary tests show the outline structure and advance widths to be 100% compatible.

<img width="1400" alt="OpenSansVsNotoSans_Light" src="https://user-images.githubusercontent.com/6576107/83887244-2cbe2780-a716-11ea-80f9-57486fe092de.png">

cc:
@davelab6
@m4rc1e
@moyogo
@djrrb
@michelleperham

**Comment by pichotta** [comment]
In the /docs folder in the /master branch there are comparisons of the common masters between the OpenSans being served and the OpenSans based on Noto.

My general impression is that in the new data the fidelity of the spacing and the outline shapes and positioning are an improvement. There are still some expected variations in adv width which are mostly related to improvements and in the back end of the glyph set. The differences are not more than with the versions on the larem0 repo.  (An advance width difference of 20 on 2048 would translate to an approx diff of 10 on 1000UPM) The threshold shows differences between adv widths.

Other things to note are the increased number of styles; the foundation for an expansion of glyphs and languages; potential for a two axes wght, wdth variable font.


cc:
@davelab6
@m4rc1e
@moyogo
@djrrb

**Comment by pichotta** [comment]
@m4rc1e 
The /docs folder in the master branch also has overlay and threshold comparisons for the intermediates.

**Comment by pichotta** [comment]
The current strategy is decidedly an improvement.
