### ISSUE TITLE
Font Info: Legal and Parties

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/opensans-1#32]
@m4rc1e 

What would you like stated in these fields for the upgrade to Open Sans?

Trademark: 
Designer:
Designer URL:
Manufacturer
Manufacturer URL:

cc: @moyogo

**Comment by moyogo** [comment]
For comparison here are the original OpenSans values and the Noto Sans values.
|  | OpenSans | NotoSans |
|--|------------|----------|
| trademark | Open Sans is a trademark of Google and may be registered in certain jurisdictions. | Noto is a trademark of Google LLC |
| openTypeNameDesigner | *N/A* | Monotype Design Team
| openTypeNameDesignerURL | http://www.ascendercorp.com/typedesigners.html | http://www.monotype.com/studio |
| openTypeNameManufacturer | Ascender Corporation | Monotype Imaging Inc. |
| openTypeNameManufacturerURL | http://www.ascendercorp.com/ | http://www.google.com/get/noto/ |

@m4rc1e Does it make sense to keep the trademark as in OpenSans, and use the values of Noto Sans for Designer, DesignerURL, Manufacturer? What about ManufacturerURL?

**Comment by m4rc1e** [comment]
@davelab6 thoughts?

**Comment by pichotta** [comment]
@davelab6
What would Google like stated in these fields for the upgrade to OpenSans?  see above comparison

Trademark:

Designer:
Designer URL:

Manufacturer
Manufacturer URL:

**Comment by pichotta** [comment]
The info was left the same as the repo from which this was forked.
