### ISSUE TITLE
Family design grid and 'Cond ExtraBold Italic'

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/opensans-1#8]
https://github.com/laerm0/opensans/issues/30

**Comment by pichotta** [comment]
> laerm0 commented
> It was interpolated/extrapolated from the ExtraBold Italic and the Bold Condensed.

The extrapolation across slope and with a lighter weight has some distortion of fit, glyph widths, stroke width and shape.

**Comment by pichotta** [comment]
![CondExtraBoldItal](https://user-images.githubusercontent.com/6576107/80048402-177e9800-84de-11ea-900e-e0f0e6ee8fdf.png)

> laerm0 commented 
> The CondExtraBoldItalic was interpolated/extrapolated from the ExtraBold Italic and the Bold Condensed.
>   
> davelab6 commented 2 days ago
> Can it be safely discarded?
> 
> Owner
> laerm0 commented yesterday
> Discard that weight? Not if you want a gap in the weights… (I probably don't understand the question.)

**Comment by pichotta** [comment]
If the existing CondExtraBoldItalic is not a viable master then what is the short-term and long-term resolution?  Some options or combinations of options:

a) produce separate VF fonts now to match the current styles and design space served.
b) commission the drawing of a new master CondExtraBoldItalic master extreme pole.
c) investigate and compare outlines with "NotoSans_Cond_ExtraBold_Italic"
d) produce VF fonts after the CondExtraBoldItalic is drawn. 
e) or, ?

![OpenSans family grid fgc](https://user-images.githubusercontent.com/6576107/80049440-e489d380-84e0-11ea-86d9-fe51ab8caa39.png)
----

![OpenSans grid sources](https://user-images.githubusercontent.com/6576107/80049446-e784c400-84e0-11ea-9035-0cd1a4bf84b7.png)
----

![OpenSans CondExtraBoldItal](https://user-images.githubusercontent.com/6576107/80049463-f10e2c00-84e0-11ea-94f1-69a717eb741c.png)
----

![NotoSansCondExtraBoldItalic 2020-04-22 at 9 30 27 PM](https://user-images.githubusercontent.com/6576107/80049469-f3708600-84e0-11ea-8f22-f61297ec2362.png)

@davelab6
@moyogo 
@m4rc1e

**Comment by pichotta** [comment]
Dave and I talked this afternoon about **OpenSans**.

The short term goal will be to focus
on making a [wght].ttf for 
the styles in the normal width.

The normal widths contain the most
compression benefits for the family.

There will be two VF files which 
will cover the current instances.
one for the romans and,
one for the italics.

OpenSans[wght].ttf
Light
Regular
Semi-Bold
Bold
Extra-Bold

OpenSans-Italic[wght].ttf
_Light Italic
Regular Italic
Semi-Bold Italic
Bold Italic
Extra-Bold Italic_


@moyogo 

cc:
@davelab6
@m4rc1e
@michelleperham

**Comment by davelab6** [comment]
https://fonts.google.com/specimen/Open+Sans has 300..800 - where are the 100 and 900 you mention coming from? :)

**Comment by pichotta** [comment]
Yes, you are right. I was looking into whether there was a relationship to the NotoSans hinted versions. Correcting the previous entry to reflect the range of OpenSans from Light (300) to Extra-Bold (800).

**Comment by davelab6** [comment]
Ah, makes sense :) Noto Sans has a slightly different design, so can be used as a reference, but glyphs from it can not be directly merged in to Open Sans, AFAIK they need hand-tuning from there

**Comment by davelab6** [comment]
> The short term goal will be to focus on making a [wght].ttf for the styles in the normal width.

Therefore I suggest you can close this issue :)
